### ISSUE TITLE
Shuttlebays - Issues with remote opening doors from shuttles

### ISSUE THREAD

**Issue by HPringles** [dapperrobotbear/Stage9#37]
- If shuttlebay 2 is remote opened, and you are still inside shuttlebay 1, the door closes and the shuttlebay unloads, meaning you have to merge through the hull of the ship to escape

- When going from shuttlebay 1(I assume the same happens when going from 2, but not tested) if shuttlebay 2 is remote opened, and you get stuck in the shuttle(which always happens due to another listed bug), you need to emergency transport, however doing so transports you back to shuttlebay 1, as it was the last used turbolift. This causes the deck to be unloaded and it does not reload.

- After this, I used to turbolift to move to shuttlebay 2. In it's default state the door is closed, meaning the ship outside does not need to be loaded, however if the door has been remote opened it is not in its defaul state, the ship model does not spawn in this instance

- After closing and reopening shuttlebay 2's door to make the ship appear, I flew out and back to shuttlebay 1. After hitting the remote open button I got the message 'fatal error' and the game crashed.

- Related Images - https://imgur.com/a/ta54k

- PC SPECS : Intel i7-4790, 16GB RAM, 2tb HDD, 120gb SSD, GTX 970 GPU

**Comment by scragnog** [comment]
@dapperrobotbear what do you reckon about this one? Obviously there's not enough checks in-place to disable functions if the player is not in the location we'd expect them to be (which for the remote open buttons in the shuttle, would be outside the ship). I'll assign this to you for now. If you think it's something straightforward that I can have a crack at, send it back to me :-)

**Comment by sylario** [comment]
Shuttle bay door 1 open => go in a shuttle => open shuttle bay 1.  The shuttle bay door go from open to playing animation opening.

**Comment by sylario** [comment]
![test](https://user-images.githubusercontent.com/95630/33293264-83fb5376-d3cc-11e7-8cd6-82cbccb5564f.png)

**Comment by Gary-Baggins** [comment]
I believe this could be a duplicate of #129 @TheStrato @HPringles

**Comment by TheStrato** [comment]
I linked the two tickets since they both have a lot of info on them.

**Comment by dapperrobotbear** [comment]
I think this was fixed in QA4.

**Comment by TheStrato** [comment]
Changed the pipeline accordingly.

**Comment by kaadaq** [comment]
V0010-HF1 Testing:

Bullet#1:   So, the "Open Shuttlebay 2" button does not appear on the shuttle display until you have cleared the bay doors, so #1, as described, cannot occur.   HOWEVER....

If you park right outside the bay, trigger the remote open, and then fly back into the bay before the door closes, the bay unloads.   So, technically still an issue, but only in very specific circumstances.
![image](https://user-images.githubusercontent.com/34050343/37768245-4df4dd5c-2da3-11e8-8aa0-4ba5764347a4.png)

Bullet #2: Remote transport from a shuttle with the bay door closed is also still an issue:
![image](https://user-images.githubusercontent.com/34050343/37768399-dc4403bc-2da3-11e8-81a3-d12c96082d5a.png)

Bullet #3: Still an issue:
![image](https://user-images.githubusercontent.com/34050343/37768887-86bc79d6-2da5-11e8-9d50-dc5e9f13108b.png)

Bullet #4:  Could not reproduce.   Was able to re-open main shuttlebay door without crashing.
@TheStrato, please put back in pipeline.

**Comment by TheStrato** [comment]
Still a bit buggy on several counts.

**Comment by tenko23** [comment]
@TheStrato @HPringles - moved to Bugz.
